### PR TITLE
Feature/global webhooks for app

### LINKED ISSUE #31: Global webhook url for push events
For apps integrating locative, currently there are 2 options to get push events for your users.

 - You set up a mqtt connection per user
 - You set up a socket.io connection per user

For each of these you need the username and password of the user, which you in fact don't want to store for security reasons. (that's the whole purpose of using OAUth)
The managing of these subscriptions per user can be tedious and does not scale

I suggest a third one, configuring a single callback url on app level that is triggered for all the users linked to the app. This involves some kind of 'Automatic subscription' when a new user is linked to the app.
This app-global `webhook url` is set up when creating the OAuth app.

eg:
https://dev.netatmo.com/doc/webhooks

Implementation could look like this:

* server receives fencelog from locative app
* server checks if user has oauth apps connected
* for each of the apps check if there is a global callback url set up
* if set do a post to the callback url with as body the fencelog (make sure there is a way to validate that the request is actually coming from locative, see netatmo example)

@kimar what do you think about this?

### PR DESCRIPTION
**Pull request by jasperdevrient**
Fixes #31. The logic for sending the data to the webhooks is in the ` triggerFenceLog` function. I didn't work with the Subscriptions model because when the developper changes the webhook URI that would implicate that all the subscriptions for that app would need to be changed. I have also added some indexes so that the fetching of the clients and acces tokens goes faster.

### CODE REVIEW

**Comment by kimar** [comment]
@jasperdevrient I've resolved the conflicts introduced by my changes to `master`, could you throw a quick look if `lib/trigger.js` is good this way, basically what I did was removing the MQTT publisher. For me this looks good so far, if you're on the same page I'd like to merge this into master.

**Comment by jasperdevrient** [comment]
@kimar this looks good to me. The only thing that might be needed to be changed in the future is the console.log when an error occors on a webhook.

**Comment by kimar** [comment]
Awesome thx @jasperdevrient :+1:

**Comment by francisdb** [comment]
👍

**Pull request merged**
